spring.datasource.url=jdbc:postgresql://localhost:5432/finalizatcc
spring.datasource.username=postgres
spring.datasource.password=12345

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Swagger
springdoc.swagger-ui.path=/

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.show-extensions=true

# Informações da API
app.name=Sistema de Gerenciamento de Tabalhos de Conclusão de Curso
app.description=API REST para gestão de Tabalhos de Conclusão de Curso (TCC) em uma instituição de ensino.
app.version=1.0.0
app.author=Pedro Vitor Barbosa Florentino e Lara Bezerra de Menezes
app.email=pedro.florentino@academico.ifpb.edu.br, menezes.lara@academico.ifpb.edu.br

# JWT Configuration
jwt.secret=sua-chave-secreta-super-segura-min-32-caracteres-para-desenvolvimento
jwt.expiration=86400000
